<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>61aaecbc-0c29-4ef4-bf9b-c7a16d52edaa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemporalCommunity.Aspire.Hosting\TemporalCommunity.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\SampleClient\SampleClient.csproj" />
    <ProjectReference Include="..\SampleWorker\SampleWorker.csproj" />
  </ItemGroup>
</Project>
