<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>aaeb5a6f-1f37-4a16-bdd7-7eeb78115da5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemporalCommunity.Aspire.Hosting\TemporalCommunity.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\SampleClient\SampleClient.csproj" />
    <ProjectReference Include="..\SampleWorker\SampleWorker.csproj" />
  </ItemGroup>
</Project>
